FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python packages
COPY docker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your app
WORKDIR /app
COPY Backend/RAG.py RAG.py
COPY docker/main_docker.py main.py
CMD ["python", "-u", "main.py"]