services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "8001:8001" # Redis Insights
    enviroment:
      - REDIS_ARGS= "--requirepass ${DB_PASSWORD}"
    env_file:
      - secrets.env
    volumes:
      - ./data:/data
    networks:
      - RAG_network

  python_api:
    build: 
      context: .
      dockerfile: Dockerfile.RAG
    depends_on:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ${DOCUMENT_FOLDER}:/app/documentos
    env_file:
      - settigns.env
      - secrets.env
    networks:
      - RAG_network
  webui:
    image: nginx:alpine
    depends_on:
      - redis
      - python_api
    ports:
      - "80:80"
    volumes:
      - ./webui:/usr/share/nginx/html
    networks:
      - RAG_network

networks:
  RAG_network:

# volumes:
#   nginx_volume:

#   python_volume: