FROM nginx:alpine

# Delete by default page
RUN rm -rf /usr/share/nginx/html/*

# Copy the frontend
COPY ../../Frontend /usr/share/nginx/html/

# Use the NGINX configuration
# COPY docker/compose/nginx.conf /etc/nginx/conf.d/default.conf
