services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      # - "6379:6379"
      - "8361:8001" # Redis Insights
    environment:
      - REDIS_ARGS= --requirepass ${DB_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - RAG_network

  python_api:
    image: miguelgp13/rag-backend:2.0.0-lite
    container_name: backend
    depends_on:
      - redis
    ports:
      - "13001:13001"
    env_file:
      - settings.env
      - .env
    volumes:
      - backend-data:/app/Backend/files
    networks:
      - RAG_network
    
  frontend:
    image: miguelgp13/rag-frontend:2.0.1
    container_name: frontend
    ports:
      - "1380:80"
    networks:
      - RAG_network
      
networks:
  RAG_network:

volumes:
  redis-data:

  backend-data: